services:
  - type: web
    name: hrms_bitbyte_mobileapp-1
    runtime: python
    plan: free
    rootDir: backend
    branch: main
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --timeout 300 --graceful-timeout 30
    autoDeployTrigger: commit
    envVars:
      - key: CLIENT_VISIT_CLOUDINARY_CLOUD_NAME
        value: duc0r8bd5
      - key: CLIENT_VISIT_CLOUDINARY_API_KEY
        sync: false
      - key: CLIENT_VISIT_CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_VISIT_CLOUDINARY_FOLDER
        value: hrms-client-visits
