# Generated by Django 6.0.6 on 2026-06-29 12:04

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_add_employee_role_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('hr', 'HR'), ('marketing', 'Marketing'), ('digital_marketing', 'Digital Marketing'), ('webapp', 'WebApp'), ('mobile_app', 'Mobile App'), ('sales', 'Sales')], max_length=50)),
                ('designation', models.CharField(choices=[('associate', 'Associate'), ('intern', 'Intern'), ('tl', 'TL'), ('ceo', 'CEO'), ('md', 'MD')], max_length=50)),
                ('date_of_joining', models.DateField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=20)),
                ('reporting_tl', models.CharField(blank=True, max_length=100)),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('otc', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('personal_email', models.EmailField(max_length=254)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], max_length=20)),
                ('marital_other', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('nationality', models.CharField(max_length=50)),
                ('current_door', models.CharField(blank=True, max_length=20)),
                ('current_street', models.CharField(blank=True, max_length=100)),
                ('current_address2', models.CharField(blank=True, max_length=100)),
                ('current_city', models.CharField(max_length=50)),
                ('current_state', models.CharField(max_length=50)),
                ('permanent_door', models.CharField(blank=True, max_length=20)),
                ('permanent_street', models.CharField(blank=True, max_length=100)),
                ('permanent_address2', models.CharField(blank=True, max_length=100)),
                ('permanent_city', models.CharField(max_length=50)),
                ('permanent_state', models.CharField(max_length=50)),
                ('emergency_name', models.CharField(max_length=50)),
                ('emergency_relationship', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('passport', models.CharField(blank=True, max_length=20)),
                ('driving_license', models.CharField(blank=True, max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('year_of_passing', models.CharField(max_length=4)),
                ('percentage', models.CharField(max_length=10)),
                ('account_holder', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('branch_name', models.CharField(max_length=100)),
                ('is_experienced', models.BooleanField(default=False)),
                ('prev_company', models.CharField(blank=True, max_length=100)),
                ('prev_designation', models.CharField(blank=True, max_length=100)),
                ('prev_experience', models.CharField(blank=True, max_length=10)),
                ('prev_last_working_day', models.CharField(blank=True, max_length=20)),
                ('doc_passport_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_aadhar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_pan', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_bank_passbook', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_10th', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_12th', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_degree', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_consolidated', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_resume', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_experience_cert', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_relieving', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_salary_slips', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_passport_copy', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_driving', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('doc_vaccination', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MdMeeting',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('ceo', 'CEO'), ('md', 'MD'), ('hr', 'HR'), ('finance', 'Finance'), ('marketing', 'Marketing Team'), ('it', 'IT Team'), ('admin', 'Admin'), ('manager', 'Manager'), ('tl', 'TL')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeaccount',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='hrms.employeeregistration'),
        ),
    ]
