# Generated by Django 6.0.6 on 2026-07-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0023_user_work_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('company_type', models.CharField(blank=True, max_length=80)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('founded_on', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=30)),
                ('esi_number', models.CharField(blank=True, max_length=40)),
                ('pf_code', models.CharField(blank=True, max_length=40)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeaccount',
            name='department',
            field=models.CharField(choices=[('web_application_development', 'Web Application Development'), ('mobile_application_development', 'Mobile Application Development'), ('marketing', 'Marketing'), ('digital_marketing', 'Digital Marketing'), ('technical_support', 'Technical Support'), ('management', 'Management'), ('internship_trainee', 'Internship / Trainee'), ('hr', 'HR'), ('webapp', 'WebApp'), ('mobile_app', 'Mobile App'), ('sales', 'Sales')], max_length=50),
        ),
        migrations.CreateModel(
            name='OrganizationBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('is_head_office', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_head_office', 'name'],
                'unique_together': {('owner_user_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('business_unit', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('reports_to', models.CharField(blank=True, max_length=120)),
                ('filled_positions', models.PositiveIntegerField(default=0)),
                ('vacant_positions', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner_user_id', 'name', 'department')},
            },
        ),
    ]
