# Generated by Django 6.0.6 on 2026-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0024_organizationprofile_alter_employeeaccount_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(db_index=True, max_length=40)),
                ('department_key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('head_user_id', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner_user_id', 'code'), ('owner_user_id', 'department_key')},
            },
        ),
    ]
