# Generated by Django 6.0.6 on 2026-07-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0030_announcement_assetinventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='designation',
            field=models.CharField(choices=[('associate', 'Associate'), ('intern', 'Intern'), ('tl', 'TL'), ('admin', 'Admin'), ('hr', 'HR'), ('ceo', 'CEO'), ('md', 'MD'), ('director', 'Executive Director'), ('manager', 'Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('ceo', 'CEO'), ('md', 'MD'), ('director', 'Executive Director'), ('hr', 'HR'), ('finance', 'Finance'), ('marketing', 'Marketing Team'), ('it', 'IT Team'), ('admin', 'Admin'), ('manager', 'Manager'), ('tl', 'TL'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
