# Generated by Django 6.0.6 on 2026-07-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0036_employeeapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeapprovalrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='approval_attachments/'),
        ),
        migrations.AddField(
            model_name='employeeapprovalrequest',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employeeapprovalrequest',
            name='posted_by',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='employeeapprovalrequest',
            name='scheduled_post',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
