# Generated by Django 6.0.6 on 2026-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0037_employeeapprovalrequest_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeapprovalrequest',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeapprovalrequest',
            name='leave_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
