# Generated by Django 6.0.6 on 2026-08-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0051_alter_mdmeeting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdmeeting',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='recruitmentjobopening',
            name='location',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
