"""
Django settings for hrms project.
 
Generated by 'django-admin startproject' using Django 6.0.6.
 
For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
 
from pathlib import Path
from dotenv import load_dotenv
import os
from urllib.parse import parse_qs, unquote, urlparse
import cloudinary
 
load_dotenv()

# All Cloudinary uploads (HRMS profiles, documents, and client visits) use
# the same single Cloudinary account. Reads CLIENT_VISIT_CLOUDINARY_* first,
# then falls back to CLOUDINARY_* so existing Render / server env vars
# continue to work without any dashboard changes.
_cv_cloud_name = (
    os.getenv('CLIENT_VISIT_CLOUDINARY_CLOUD_NAME', '').strip()
    or os.getenv('CLOUDINARY_CLOUD_NAME', '').strip()
)
_cv_api_key = (
    os.getenv('CLIENT_VISIT_CLOUDINARY_API_KEY', '').strip()
    or os.getenv('CLOUDINARY_API_KEY', '').strip()
)
_cv_api_secret = (
    os.getenv('CLIENT_VISIT_CLOUDINARY_API_SECRET', '').strip()
    or os.getenv('CLOUDINARY_API_SECRET', '').strip()
)

cloudinary.config(
    cloud_name=_cv_cloud_name,
    api_key=_cv_api_key,
    api_secret=_cv_api_secret,
    secure=True,
)

CLIENT_VISIT_CLOUDINARY_STORAGE = {
    'cloud_name': _cv_cloud_name,
    'api_key': _cv_api_key,
    'api_secret': _cv_api_secret,
    'folder': os.getenv('CLIENT_VISIT_CLOUDINARY_FOLDER', 'hrms-client-visits').strip(),
}
 
BASE_DIR = Path(__file__).resolve().parent.parent
 
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rp^&)&+jteiea(7!zy4iy3p5bn^772pe3qpic#qxhcatya6o*6'
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
 
ALLOWED_HOSTS = ['*']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
 
 
# Application definition
 
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
# ]
 
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'hrms',
    'client_visits',
]
 
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # First la irukkanum bro!
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
database_url = os.getenv('DATABASE_URL', '').strip()
if database_url:
    parsed_database_url = urlparse(database_url)
    database_options = {
        key: values[-1]
        for key, values in parse_qs(parsed_database_url.query).items()
        if values
    }
    database_options.setdefault('connect_timeout', 15)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed_database_url.path.lstrip('/'),
            'USER': unquote(parsed_database_url.username or ''),
            'PASSWORD': unquote(parsed_database_url.password or ''),
            'HOST': parsed_database_url.hostname or '',
            'PORT': str(parsed_database_url.port or 5432),
            'OPTIONS': database_options,
            'CONN_MAX_AGE': 300,
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': '5432',
            'OPTIONS': {
                'sslmode': 'require',
                'connect_timeout': 15,
            },
            'CONN_MAX_AGE': 300,
            'CONN_HEALTH_CHECKS': True,
        }
    }
 
CORS_ALLOW_ALL_ORIGINS = True
 
ROOT_URLCONF = 'backend.urls'
 
AUTH_USER_MODEL = 'hrms.User'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'backend.wsgi.application'
 
 
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
 
 
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
 
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
 
LANGUAGE_CODE = 'en-us'
 
TIME_ZONE = 'UTC'
 
USE_I18N = True
 
USE_TZ = True
 
 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
 
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
 
