class ClientVisitServiceItem {
  final String id;
  final String module;
  final String name;
  final String description;
  final String unit;
  final String frequency;
  final String payable;
  final List<int> prices;

  const ClientVisitServiceItem({
    required this.id,
    required this.module,
    required this.name,
    required this.description,
    required this.unit,
    required this.frequency,
    required this.payable,
    required this.prices,
  });
}

const clientVisitPackageNames = [
  'Starter',
  'Basic',
  'Standard',
  'Premium',
  'Enterprise',
];

const clientVisitServiceModules = [
  'Digital Marketing',
  'SEO',
  'Performance Marketing',
  'Web Apps',
  'Hosting',
  'Personal Branding',
  'Mobile Apps',
];

const clientVisitServiceCatalog = <ClientVisitServiceItem>[
  ClientVisitServiceItem(
    id: 'los_01_brand_logo_designs',
    module: 'Digital Marketing',
    name: 'Brand Logo Designs',
    description: 'Primary custom logo design.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [1790, 1890, 1990, 2490, 2990],
  ),
  ClientVisitServiceItem(
    id: 'los_02_brand_identity_kit',
    module: 'Digital Marketing',
    name: 'Brand Identity Kit',
    description: 'Logos, colours and fonts in English and Tamil.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [3490, 3490, 3490, 3990, 3990],
  ),
  ClientVisitServiceItem(
    id: 'los_03_social_accounts_creation',
    module: 'Digital Marketing',
    name: 'Social Media Accounts Creation',
    description:
        'Account setup for Facebook, Instagram, X, LinkedIn, WhatsApp Business profile and channel groups.',
    unit: 'Per Group',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [690, 690, 690, 990, 990],
  ),
  ClientVisitServiceItem(
    id: 'los_04_social_accounts_handling',
    module: 'Digital Marketing',
    name: 'Social Media Accounts Handling',
    description:
        'Account handling with image and video posts, descriptions, hashtags and follower replies.',
    unit: 'Per Platform',
    frequency: 'Monthly',
    payable: 'Monthly',
    prices: [1740, 1990, 2240, 2490, 2490],
  ),
  ClientVisitServiceItem(
    id: 'los_05_photo_design',
    module: 'Digital Marketing',
    name: 'Photo Design',
    description:
        'Static image creatives for advertisements and social media with rich product backgrounds.',
    unit: 'Per Image',
    frequency: 'Weekly',
    payable: 'Monthly',
    prices: [2090, 2390, 2690, 2990, 3290],
  ),
  ClientVisitServiceItem(
    id: 'los_06_ad_creative_image',
    module: 'Digital Marketing',
    name: 'Ad Creative Design - Image',
    description:
        'High-converting, AI-powered dynamic image creatives with sector-based backgrounds and models.',
    unit: 'Per Image',
    frequency: 'Weekly',
    payable: 'Monthly',
    prices: [3220, 3680, 4140, 4600, 5060],
  ),
  ClientVisitServiceItem(
    id: 'los_07_video_design',
    module: 'Digital Marketing',
    name: 'Video Design',
    description:
        'Short AI-powered promotional and advertisement videos with rich product backgrounds.',
    unit: 'Per Video',
    frequency: 'Weekly',
    payable: 'Monthly',
    prices: [2100, 2400, 2700, 3000, 3300],
  ),
  ClientVisitServiceItem(
    id: 'los_08_ad_creative_video',
    module: 'Digital Marketing',
    name: 'Ad Creative Design - Video',
    description:
        'High-converting dynamic video creatives for advertisements and social media with AI-powered models.',
    unit: 'Per Video',
    frequency: 'Weekly',
    payable: 'Monthly',
    prices: [3220, 3680, 4140, 4600, 5060],
  ),
  ClientVisitServiceItem(
    id: 'los_09_live_photo_shoot',
    module: 'Digital Marketing',
    name: 'Live Photo Shoot at Site',
    description:
        'Indoor or outdoor product photo shoot at the client location: up to 250 photos per day or 125 per half-day.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [6990, 6990, 6990, 6990, 6990],
  ),
  ClientVisitServiceItem(
    id: 'los_10_ad_copywriting',
    module: 'Digital Marketing',
    name: 'Ad Copywriting',
    description:
        'Platform-focused, high-converting advertisement and post copy, descriptions and hashtags.',
    unit: 'Per Service',
    frequency: 'Weekly',
    payable: 'Monthly',
    prices: [990, 990, 990, 990, 990],
  ),
  ClientVisitServiceItem(
    id: 'los_11_festival_package',
    module: 'Digital Marketing',
    name: 'Digital Marketing Festival Package',
    description:
        'AI-powered image and video creatives covering three selected festive weeks.',
    unit: 'Per Service',
    frequency: 'Weekly',
    payable: 'One Time',
    prices: [6990, 6990, 6990, 6990, 6990],
  ),
  ClientVisitServiceItem(
    id: 'los_12_basic_seo',
    module: 'SEO',
    name: 'Basic SEO',
    description: 'On-page optimization and SEO fundamentals.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [6990, 6990, 6990, 6990, 6990],
  ),
  ClientVisitServiceItem(
    id: 'los_13_advanced_seo',
    module: 'SEO',
    name: 'Advanced SEO',
    description: 'On-page SEO, technical SEO, content and backlinks.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [13990, 13990, 13990, 13990, 13990],
  ),
  ClientVisitServiceItem(
    id: 'los_14_enterprise_seo',
    module: 'SEO',
    name: 'Enterprise SEO',
    description: 'Full-scale SEO strategy and execution.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [27990, 27990, 27990, 27990, 27990],
  ),
  ClientVisitServiceItem(
    id: 'los_15_local_seo',
    module: 'SEO',
    name: 'Local SEO',
    description: 'Google Business Profile optimization.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [3490, 3490, 3490, 3490, 3490],
  ),
  ClientVisitServiceItem(
    id: 'los_16_seo_content_writing',
    module: 'SEO',
    name: 'SEO Content Writing',
    description:
        'SEO-optimized article writing with research and on-page optimization by package.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [990, 1490, 1990, 2490, 2990],
  ),
  ClientVisitServiceItem(
    id: 'los_17_competitor_analysis',
    module: 'SEO',
    name: 'Competitor Analysis Report',
    description: 'Market, competitor and keyword insights.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [3490, 3490, 4490, 4990, 5490],
  ),
  ClientVisitServiceItem(
    id: 'los_18_google_ads',
    module: 'Performance Marketing',
    name: 'Google Ads Campaign',
    description:
        'Search, Display and Performance campaign management and optimization.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [39990, 44990, 49990, 54990, 59990],
  ),
  ClientVisitServiceItem(
    id: 'los_19_conversion_tracking',
    module: 'Performance Marketing',
    name: 'Conversion Tracking Setup',
    description: 'GA4, Pixel tracking and Google Search Console integration.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [3490, 3990, 4490, 4990, 5490],
  ),
  ClientVisitServiceItem(
    id: 'los_20_meta_ads',
    module: 'Performance Marketing',
    name: 'Meta Ads Campaign',
    description:
        'Facebook and Instagram advertisement management and optimization.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [31490, 35990, 40440, 44990, 49990],
  ),
  ClientVisitServiceItem(
    id: 'los_21_basic_website',
    module: 'Web Apps',
    name: 'Basic Website Design',
    description: 'Website design with up to four pages and handling.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [3490, 3990, 4490, 4990, 5490],
  ),
  ClientVisitServiceItem(
    id: 'los_22_dynamic_website',
    module: 'Web Apps',
    name: 'Dynamic Website Design',
    description:
        'Attractive UI/UX website with more than four and up to fifteen pages or five modules, without updates.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [17490, 19990, 22490, 24990, 27490],
  ),
  ClientVisitServiceItem(
    id: 'los_23_website_content_updates',
    module: 'Web Apps',
    name: 'Advanced Website Content Updates',
    description: 'Page content changes after initial website setup and launch.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [3490, 3990, 4490, 4990, 5490],
  ),
  ClientVisitServiceItem(
    id: 'los_24_website_module_updates',
    module: 'Web Apps',
    name: 'Advanced Website Module Updates',
    description:
        'Module and image additions after initial website setup and launch.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [6990, 7990, 8990, 9990, 10990],
  ),
  ClientVisitServiceItem(
    id: 'los_25_ecommerce_website',
    module: 'Web Apps',
    name: 'E-Commerce Website',
    description: 'Complete online store setup with payment gateway.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [49990, 49990, 49990, 49990, 49990],
  ),
  ClientVisitServiceItem(
    id: 'los_26_website_maintenance',
    module: 'Web Apps',
    name: 'Website Maintenance',
    description: 'Monthly website, system and security updates with support.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'Monthly',
    prices: [2990, 2990, 2990, 2990, 2990],
  ),
  ClientVisitServiceItem(
    id: 'los_27_speed_optimization',
    module: 'Web Apps',
    name: 'Website Speed Optimization',
    description:
        'Performance, page-loading, enhancement and security improvements.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [4990, 4990, 4990, 4990, 4990],
  ),
  ClientVisitServiceItem(
    id: 'los_28_web_billing_system',
    module: 'Web Apps',
    name: 'Web Billing System',
    description:
        'Web-based billing system with live scheduled automated reporting.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [13900, 15990, 17990, 19990, 21990],
  ),
  ClientVisitServiceItem(
    id: 'los_29_domain_registration',
    module: 'Hosting',
    name: 'Domain Registration in AWS Cloud',
    description:
        'New .com, .org or .in domain registration and activation in Amazon Web Services.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [4990, 4990, 4990, 4990, 4990],
  ),
  ClientVisitServiceItem(
    id: 'los_30_mail_server',
    module: 'Hosting',
    name: 'Business Mail Server Registration',
    description:
        'Business-class company email registration through Microsoft Cloud or Google Mail.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [749, 749, 749, 749, 749],
  ),
  ClientVisitServiceItem(
    id: 'los_31_aws_server_setup',
    module: 'Hosting',
    name: 'AWS DNS, Mail and Web Server Setup',
    description:
        'DNS, mail and web server configuration, site mounting, hosting and performance assessment with round-the-clock service.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [9990, 9990, 9990, 9990, 9990],
  ),
  ClientVisitServiceItem(
    id: 'los_32_personal_branding',
    module: 'Personal Branding',
    name: 'Personal Branding',
    description:
        'Host-ready, high-value AI-powered personal branding images and videos.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'Monthly',
    prices: [4990, 4990, 4990, 4990, 4990],
  ),
  ClientVisitServiceItem(
    id: 'los_33_consulting',
    module: 'Personal Branding',
    name: 'Consulting Charges',
    description: 'Consultation and planning services.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [9990, 9990, 9990, 9990, 9990],
  ),
  ClientVisitServiceItem(
    id: 'los_34_responsive_pages',
    module: 'Web Apps',
    name: 'Responsive Web Pages',
    description: 'Adaptive React pages for desktop, mobile and tablet screens.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [8750, 9990, 11250, 12490, 13750],
  ),
  ClientVisitServiceItem(
    id: 'los_35_android_static_app',
    module: 'Mobile Apps',
    name: 'Android Static Mobile Application',
    description:
        'Static Android application targeting Android 13 and later, with package-based screen limits.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [38490, 43990, 49490, 54990, 59990],
  ),
  ClientVisitServiceItem(
    id: 'los_36_android_dynamic_app',
    module: 'Mobile Apps',
    name: 'Android Dynamic Mobile Application',
    description:
        'Dynamic Android application targeting Android 13 and later with database and admin support by package.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [59490, 67990, 76490, 84990, 93490],
  ),
  ClientVisitServiceItem(
    id: 'los_37_google_play_setup',
    module: 'Mobile Apps',
    name: 'Google Play Store Configuration',
    description: 'D-U-N-S number purchase and Google Play Store configuration.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [12490, 12490, 12490, 12490, 12490],
  ),
  ClientVisitServiceItem(
    id: 'los_38_android_maintenance',
    module: 'Mobile Apps',
    name: 'Android Application Maintenance',
    description: 'Android application and Google Play Store maintenance.',
    unit: 'Per Service',
    frequency: 'Monthly',
    payable: 'Monthly',
    prices: [5750, 5750, 5750, 5750, 5750],
  ),
  ClientVisitServiceItem(
    id: 'los_39_android_enhancements',
    module: 'Mobile Apps',
    name: 'Android Enhancements and Security',
    description:
        'Application enhancements and security updates for major Android releases and app updates.',
    unit: 'Per Service',
    frequency: 'Monthly',
    payable: 'Monthly',
    prices: [9990, 9990, 9990, 9990, 9990],
  ),
  ClientVisitServiceItem(
    id: 'los_40_ios_static_app',
    module: 'Mobile Apps',
    name: 'Apple iOS Static Mobile Application',
    description:
        'Static Apple iOS application with package-based screen limits.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [100490, 119990, 134990, 149990, 164990],
  ),
  ClientVisitServiceItem(
    id: 'los_41_ios_dynamic_app',
    module: 'Mobile Apps',
    name: 'Apple iOS Dynamic Mobile Application',
    description:
        'Dynamic iOS application with database, admin panel and analytics support by package.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [59490, 67990, 76490, 84990, 93490],
  ),
  ClientVisitServiceItem(
    id: 'los_42_ios_store_setup',
    module: 'Mobile Apps',
    name: 'Apple App Store Configuration',
    description: 'D-U-N-S number purchase and Apple App Store configuration.',
    unit: 'Per Service',
    frequency: 'One Time',
    payable: 'One Time',
    prices: [12490, 12490, 12490, 12490, 12490],
  ),
  ClientVisitServiceItem(
    id: 'los_43_ios_maintenance',
    module: 'Mobile Apps',
    name: 'iOS Application Maintenance',
    description: 'iOS application and Apple App Store maintenance.',
    unit: 'Per Service',
    frequency: 'Monthly',
    payable: 'Monthly',
    prices: [9990, 9990, 9990, 9990, 9990],
  ),
  ClientVisitServiceItem(
    id: 'los_44_ios_enhancements',
    module: 'Mobile Apps',
    name: 'iOS Enhancements and Security',
    description:
        'Application enhancements and security updates for major iOS releases and app updates.',
    unit: 'Per Service',
    frequency: 'Monthly',
    payable: 'Monthly',
    prices: [19990, 19990, 19990, 19990, 19990],
  ),
  ClientVisitServiceItem(
    id: 'los_45_whatsapp_setup',
    module: 'Digital Marketing',
    name: 'WhatsApp Business Setup',
    description: 'WhatsApp Business account setup and catalogue creation.',
    unit: 'Per Service',
    frequency: 'Monthly',
    payable: 'Monthly',
    prices: [3990, 3990, 3990, 3990, 3990],
  ),
  ClientVisitServiceItem(
    id: 'los_46_whatsapp_catalogue',
    module: 'Digital Marketing',
    name: 'WhatsApp Catalogue Maintenance',
    description: 'WhatsApp Business catalogue updates and maintenance.',
    unit: 'Per Service',
    frequency: 'Monthly',
    payable: 'Monthly',
    prices: [1750, 2000, 2250, 2500, 2750],
  ),
  ClientVisitServiceItem(
    id: 'los_47_whatsapp_automation',
    module: 'Digital Marketing',
    name: 'WhatsApp Catalogue Automation Setup',
    description:
        'WhatsApp Business catalogue automation using n8n or Meta setup and configuration.',
    unit: 'Per Service',
    frequency: 'Monthly',
    payable: 'Monthly',
    prices: [4990, 4990, 4990, 4990, 4990],
  ),
  ClientVisitServiceItem(
    id: 'los_48_whatsapp_api_updates',
    module: 'Digital Marketing',
    name: 'WhatsApp Automation API Updates',
    description:
        'WhatsApp Business catalogue automation API calls and updates using n8n or Meta.',
    unit: 'Per Service',
    frequency: 'Monthly',
    payable: 'Monthly',
    prices: [3490, 3490, 3490, 3490, 3490],
  ),
];

ClientVisitServiceItem? clientVisitServiceById(String id) {
  for (final service in clientVisitServiceCatalog) {
    if (service.id == id) return service;
  }
  return null;
}
