# Generated by Django 6.0.6 on 2026-08-11 04:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visits', '0007_clientvisittrackinglink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVisitJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=160)),
                ('client_contact', models.CharField(blank=True, max_length=120)),
                ('meeting_purpose', models.CharField(max_length=240)),
                ('destination_address', models.TextField(blank=True)),
                ('destination_latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('destination_longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('READY', 'Ready'), ('IN_PROGRESS', 'In progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('total_distance_metres', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_duration_seconds', models.PositiveBigIntegerField(default=0)),
                ('moving_duration_seconds', models.PositiveBigIntegerField(default=0)),
                ('stationary_duration_seconds', models.PositiveBigIntegerField(default=0)),
                ('last_location_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_team_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_client_visit_journeys', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_visit_journeys', to=settings.AUTH_USER_MODEL)),
                ('source_visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_journey', to='client_visits.clientvisit')),
            ],
            options={
                'ordering': ['-scheduled_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JourneyLocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_generated_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy_metres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('speed_metres_per_second', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('captured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('sequence_number', models.PositiveBigIntegerField()),
                ('is_mocked', models.BooleanField(blank=True, null=True)),
                ('battery_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_low_accuracy', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journey_location_points', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_points', to='client_visits.clientvisitjourney')),
            ],
            options={
                'ordering': ['captured_at', 'sequence_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveBigIntegerField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='client_visits.clientvisitjourney')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientvisitjourney',
            index=models.Index(fields=['status', 'last_location_at'], name='cvj_status_last_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvisitjourney',
            index=models.Index(fields=['assigned_team_lead', 'status'], name='cvj_tl_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientvisitjourney',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['IN_PROGRESS', 'PAUSED'])), fields=('employee',), name='one_active_client_journey_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='clientvisitjourney',
            constraint=models.CheckConstraint(condition=models.Q(('destination_latitude__gte', -90), ('destination_latitude__lte', 90)), name='cvj_destination_latitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='clientvisitjourney',
            constraint=models.CheckConstraint(condition=models.Q(('destination_longitude__gte', -180), ('destination_longitude__lte', 180)), name='cvj_destination_longitude_valid'),
        ),
        migrations.AddIndex(
            model_name='journeylocationpoint',
            index=models.Index(fields=['journey', 'captured_at'], name='jlp_journey_time_idx'),
        ),
        migrations.AddIndex(
            model_name='journeylocationpoint',
            index=models.Index(fields=['journey', 'sequence_number'], name='jlp_journey_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='journeylocationpoint',
            index=models.Index(fields=['employee', 'captured_at'], name='jlp_employee_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='journeylocationpoint',
            constraint=models.UniqueConstraint(fields=('journey', 'sequence_number'), name='unique_journey_sequence_number'),
        ),
        migrations.AddConstraint(
            model_name='journeylocationpoint',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='jlp_latitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='journeylocationpoint',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='jlp_longitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='journeylocationpoint',
            constraint=models.CheckConstraint(condition=models.Q(('accuracy_metres__gte', 0)), name='jlp_accuracy_non_negative'),
        ),
        migrations.AddIndex(
            model_name='journeystop',
            index=models.Index(fields=['journey', 'started_at'], name='jstop_journey_time_idx'),
        ),
    ]
