/// Shared India state/UT and city directory used by every address form.
const Map<String, List<String>> indiaCitiesByState = {
  'Andaman and Nicobar Islands': ['Port Blair', 'Diglipur', 'Mayabunder', 'Rangat'],
  'Andhra Pradesh': ['Anantapur', 'Chittoor', 'Eluru', 'Guntur', 'Kadapa', 'Kakinada', 'Kurnool', 'Nellore', 'Ongole', 'Rajahmundry', 'Srikakulam', 'Tirupati', 'Vijayawada', 'Visakhapatnam', 'Vizianagaram'],
  'Arunachal Pradesh': ['Aalo', 'Bomdila', 'Itanagar', 'Naharlagun', 'Pasighat', 'Tawang', 'Tezu', 'Ziro'],
  'Assam': ['Barpeta', 'Bongaigaon', 'Dibrugarh', 'Dispur', 'Goalpara', 'Guwahati', 'Jorhat', 'Nagaon', 'Silchar', 'Sivasagar', 'Tezpur', 'Tinsukia'],
  'Bihar': ['Arrah', 'Begusarai', 'Bhagalpur', 'Bihar Sharif', 'Chhapra', 'Darbhanga', 'Gaya', 'Katihar', 'Muzaffarpur', 'Patna', 'Purnia', 'Saharsa'],
  'Chandigarh': ['Chandigarh'],
  'Chhattisgarh': ['Ambikapur', 'Bhilai', 'Bilaspur', 'Dhamtari', 'Durg', 'Jagdalpur', 'Korba', 'Raigarh', 'Raipur', 'Rajnandgaon'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa'],
  'Delhi': ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'North East Delhi', 'North West Delhi', 'Shahdara', 'South Delhi', 'South East Delhi', 'South West Delhi', 'West Delhi'],
  'Goa': ['Bicholim', 'Canacona', 'Mapusa', 'Margao', 'Panaji', 'Ponda', 'Vasco da Gama'],
  'Gujarat': ['Ahmedabad', 'Anand', 'Bharuch', 'Bhavnagar', 'Bhuj', 'Gandhinagar', 'Jamnagar', 'Junagadh', 'Mehsana', 'Navsari', 'Rajkot', 'Surat', 'Vadodara', 'Valsad'],
  'Haryana': ['Ambala', 'Bhiwani', 'Faridabad', 'Gurugram', 'Hisar', 'Karnal', 'Kurukshetra', 'Panipat', 'Rewari', 'Rohtak', 'Sirsa', 'Sonipat'],
  'Himachal Pradesh': ['Chamba', 'Dharamshala', 'Hamirpur', 'Kullu', 'Mandi', 'Nahan', 'Shimla', 'Solan', 'Una'],
  'Jammu and Kashmir': ['Anantnag', 'Baramulla', 'Jammu', 'Kathua', 'Kupwara', 'Poonch', 'Sopore', 'Srinagar', 'Udhampur'],
  'Jharkhand': ['Bokaro', 'Chaibasa', 'Deoghar', 'Dhanbad', 'Dumka', 'Giridih', 'Hazaribagh', 'Jamshedpur', 'Ramgarh', 'Ranchi'],
  'Karnataka': ['Bagalkot', 'Ballari', 'Belagavi', 'Bengaluru', 'Bidar', 'Chikkamagaluru', 'Chitradurga', 'Davanagere', 'Hassan', 'Hubballi', 'Kalaburagi', 'Mangaluru', 'Mysuru', 'Raichur', 'Shivamogga', 'Tumakuru', 'Udupi', 'Vijayapura'],
  'Kerala': ['Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kochi', 'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'],
  'Ladakh': ['Kargil', 'Leh'],
  'Lakshadweep': ['Agatti', 'Amini', 'Andrott', 'Kavaratti', 'Minicoy'],
  'Madhya Pradesh': ['Bhopal', 'Chhindwara', 'Dewas', 'Gwalior', 'Indore', 'Jabalpur', 'Katni', 'Khandwa', 'Ratlam', 'Rewa', 'Sagar', 'Satna', 'Ujjain'],
  'Maharashtra': ['Ahmednagar', 'Akola', 'Amravati', 'Aurangabad', 'Jalgaon', 'Kolhapur', 'Latur', 'Mumbai', 'Nagpur', 'Nanded', 'Nashik', 'Navi Mumbai', 'Pune', 'Sangli', 'Satara', 'Solapur', 'Thane'],
  'Manipur': ['Bishnupur', 'Churachandpur', 'Imphal', 'Senapati', 'Thoubal', 'Ukhrul'],
  'Meghalaya': ['Jowai', 'Nongpoh', 'Shillong', 'Tura', 'Williamnagar'],
  'Mizoram': ['Aizawl', 'Champhai', 'Kolasib', 'Lunglei', 'Serchhip'],
  'Nagaland': ['Dimapur', 'Kohima', 'Mokokchung', 'Mon', 'Tuensang', 'Wokha', 'Zunheboto'],
  'Odisha': ['Balasore', 'Baripada', 'Berhampur', 'Bhadrak', 'Bhubaneswar', 'Cuttack', 'Jharsuguda', 'Puri', 'Rourkela', 'Sambalpur'],
  'Puducherry': ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
  'Punjab': ['Amritsar', 'Bathinda', 'Firozpur', 'Hoshiarpur', 'Jalandhar', 'Ludhiana', 'Mohali', 'Pathankot', 'Patiala', 'Sangrur'],
  'Rajasthan': ['Ajmer', 'Alwar', 'Bharatpur', 'Bhilwara', 'Bikaner', 'Jaipur', 'Jaisalmer', 'Jodhpur', 'Kota', 'Sikar', 'Udaipur'],
  'Sikkim': ['Gangtok', 'Gyalshing', 'Mangan', 'Namchi', 'Rangpo'],
  'Tamil Nadu': ['Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri', 'Dindigul', 'Erode', 'Hosur', 'Kanchipuram', 'Kanyakumari', 'Karur', 'Krishnagiri', 'Madurai', 'Nagapattinam', 'Nagercoil', 'Namakkal', 'Ooty', 'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Salem', 'Sivaganga', 'Thanjavur', 'Theni', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Vellore', 'Villupuram', 'Virudhunagar'],
  'Telangana': ['Adilabad', 'Hyderabad', 'Jagtial', 'Karimnagar', 'Khammam', 'Mahbubnagar', 'Medak', 'Nalgonda', 'Nizamabad', 'Ramagundam', 'Sangareddy', 'Siddipet', 'Warangal'],
  'Tripura': ['Agartala', 'Ambassa', 'Dharmanagar', 'Kailashahar', 'Udaipur'],
  'Uttar Pradesh': ['Agra', 'Aligarh', 'Ayodhya', 'Bareilly', 'Ghaziabad', 'Gorakhpur', 'Jhansi', 'Kanpur', 'Lucknow', 'Mathura', 'Meerut', 'Moradabad', 'Noida', 'Prayagraj', 'Saharanpur', 'Varanasi'],
  'Uttarakhand': ['Almora', 'Dehradun', 'Haldwani', 'Haridwar', 'Kashipur', 'Nainital', 'Pithoragarh', 'Rishikesh', 'Roorkee', 'Rudrapur'],
  'West Bengal': ['Asansol', 'Bardhaman', 'Darjeeling', 'Durgapur', 'Haldia', 'Howrah', 'Jalpaiguri', 'Kharagpur', 'Kolkata', 'Malda', 'Siliguri'],
};

List<String> get indiaStates => indiaCitiesByState.keys.toList(growable: false);
List<String> indiaCitiesForState(String state) => indiaCitiesByState[state] ?? const [];
