import 'package:flutter/material.dart';

import 'ceo_service.dart';
import 'ceo_widgets.dart';

class CeoPerformanceMatrixScreen extends StatefulWidget {
  final String userId;
  const CeoPerformanceMatrixScreen({super.key, required this.userId});
  @override State<CeoPerformanceMatrixScreen> createState() => _State();
}

class _State extends State<CeoPerformanceMatrixScreen> {
  int _page=0; bool _busy=false; String _query=''; String _department='All'; Map<String,dynamic>? _employee;
  late String _period; late Future<Map<String,dynamic>> _future;
  @override void initState(){super.initState();final n=DateTime.now();_period='Q${((n.month-1)~/3)+1} ${n.year}';_load();}
  void _load()=>_future=CeoService().fetchPerformanceMatrix(widget.userId,_period);
  Future<void> _action(String action,Map<String,dynamic> fields)async{setState(()=>_busy=true);final r=await CeoService().updatePerformanceMatrix(widget.userId,_period,action,fields);if(!mounted)return;setState((){_busy=false;if(r['success']==true)_load();});ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('${r['message']??'Unable to save review.'}'),backgroundColor:r['success']==true?CeoColors.green:Colors.redAccent));}
  void _open(Map<String,dynamic> e,int page){setState((){_employee=e;_page=page;});}
  @override Widget build(BuildContext context)=>CeoShell(title:_titles[_page],onBack:_page==0?null:()=>setState(()=>_page--),trailing:_page==2?IconButton(onPressed:()=>_editGoals(_employee),icon:const Icon(Icons.add,color:CeoColors.cyan)):null,bottomNavigationBar:NavigationBar(selectedIndex:_page==0?0:3,onDestinationSelected:(i){if(i==0)setState(()=>_page=0);},destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),label:'Home'),NavigationDestination(icon:Icon(Icons.people_outline),label:'People'),NavigationDestination(icon:Icon(Icons.approval_outlined),label:'Approvals'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'More')]),child:FutureBuilder<Map<String,dynamic>>(future:_future,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator(color:CeoColors.cyan));if(s.hasError||s.data?['success']!=true)return Center(child:OutlinedButton(onPressed:()=>setState(_load),child:const Text('Retry performance data')));final d=s.data!;final e=_resolve(d);return Stack(children:[Positioned.fill(child:switch(_page){1=>_matrix(d),2=>_goals(e),3=>_review(e),4=>_report(e),_=>_dashboard(d)}),if(_busy)const Positioned.fill(child:ColoredBox(color:Color(0x77000000),child:Center(child:CircularProgressIndicator(color:CeoColors.cyan))))]);}));

  Widget _dashboard(Map<String,dynamic>d){final s=_map(d['summary']);final deps=_maps(d['departments']);final employees=_maps(d['employees']);return ListView(padding:const EdgeInsets.all(14),children:[_periodPicker(),CeoCard(child:Column(children:[title('Overall Performance Score',14),const SizedBox(height:12),SizedBox(width:120,height:120,child:Stack(alignment:Alignment.center,children:[CircularProgressIndicator(value:_num(s['overall_score'])/5,strokeWidth:14,color:CeoColors.cyan,backgroundColor:CeoColors.border),title('${s['overall_score']}/5',18)]))])),CeoMetricGrid(cards:[CeoMetric('Total Employees','${s['total_employees']??0}','',Icons.people,CeoColors.cyan,onTap:()=>setState(()=>_page=1)),CeoMetric('Completed Reviews','${s['completed_reviews']??0}','',Icons.task_alt,CeoColors.green),CeoMetric('High Performers','${s['high_performers']??0}','',Icons.star,CeoColors.gold),CeoMetric('At Risk','${s['at_risk']??0}','',Icons.warning,Colors.redAccent)]),const SizedBox(height:12),title('Department Overview',14),const SizedBox(height:8),...deps.map((x)=>CeoCard(child:Row(children:[Expanded(child:title('${x['name']}',11)),SizedBox(width:150,child:LinearProgressIndicator(value:_num(x['score'])/5,color:CeoColors.cyan,backgroundColor:CeoColors.border)),const SizedBox(width:8),Text('${x['score']}/5')]))),FilledButton(onPressed:()=>setState(()=>_page=1),child:const Text('Open Employee Matrix')),if(employees.isEmpty)CeoCard(child:muted('No active employees returned by backend',11))]);}
  Widget _periodPicker()=>CeoCard(onTap:_changePeriod,child:Row(children:[const Icon(Icons.calendar_month,color:CeoColors.cyan),const SizedBox(width:9),Expanded(child:title(_period,13)),const Icon(Icons.expand_more)]));
  Widget _matrix(Map<String,dynamic>d){final all=_maps(d['employees']);final deps={'All',...all.map((e)=>'${e['department']}')}.toList();final list=all.where((e)=>(_department=='All'||e['department']==_department)&&'${e['name']} ${e['employee_id']}'.toLowerCase().contains(_query.toLowerCase())).toList();return Column(children:[Padding(padding:const EdgeInsets.all(14),child:DropdownButtonFormField<String>(value:_department,items:deps.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>_department=v??'All'),decoration:const InputDecoration(labelText:'Department'))),Padding(padding:const EdgeInsets.symmetric(horizontal:14),child:TextField(onChanged:(v)=>setState(()=>_query=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Search employee'))),const SizedBox(height:10),CeoCard(child:Column(children:[title('Performance / Potential Matrix',13),const SizedBox(height:8),...List.generate(3,(row)=>Row(children:List.generate(3,(col){final count=list.where((e)=>_band(e['potential_score'])==2-row&&_band(e['performance_score'])==col).length;return Expanded(child:Container(height:58,margin:const EdgeInsets.all(3),decoration:BoxDecoration(border:Border.all(color:count>0?CeoColors.cyan:CeoColors.border),borderRadius:BorderRadius.circular(6)),child:Center(child:Text('$count'))));}).toList())).toList()])),Expanded(child:ListView(padding:const EdgeInsets.symmetric(horizontal:14),children:[title('Employees',13),const SizedBox(height:7),...list.map((e)=>CeoListTile(icon:Icons.person,titleText:'${e['name']}',subtitle:'${e['designation']} • ${e['department']} • ${e['performance_score']}/5',color:_num(e['performance_score'])>=4?CeoColors.green:_num(e['performance_score'])>0?CeoColors.gold:CeoColors.muted,onTap:()=>_open(e,2))) ]))]);}
  Widget _goals(Map<String,dynamic>?e){if(e==null)return Center(child:muted('Select an employee from the matrix',12));final goals=_maps(e['goals']);final kpis=_map(e['kpis']);return ListView(padding:const EdgeInsets.all(14),children:[_profile(e),_periodPicker(),title('Goals (${goals.length})',14),const SizedBox(height:8),if(goals.isEmpty)CeoCard(child:muted('No goals saved for this period',11)),...goals.map((g)=>CeoCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('${g['title']}',12),const SizedBox(height:8),LinearProgressIndicator(value:_num(g['progress'])/100,color:CeoColors.green,backgroundColor:CeoColors.border),const SizedBox(height:5),Row(children:[muted('Target: ${g['target_date']??'-'}',9),const Spacer(),Text('${g['progress']??0}%')])]))),title('KPIs Summary',14),const SizedBox(height:8),CeoMetricGrid(cards:kpis.entries.map((x)=>CeoMetric(x.key,'${x.value}/5','',Icons.speed,CeoColors.cyan)).toList()),FilledButton(onPressed:()=>_open(e,3),child:const Text('Review & Rating'))]);}
  Widget _review(Map<String,dynamic>?e){if(e==null)return const SizedBox();final competencies=_map(e['competency_scores']);return ListView(padding:const EdgeInsets.all(14),children:[_profile(e),CeoCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('Competency Review',14),...['Technical Skills','Problem Solving','Communication','Teamwork','Ownership'].map((name)=>_ratingRow(name,_num(competencies[name]),(v){competencies[name]=v;_employee={...e,'competency_scores':competencies};setState((){});})),])),CeoCard(child:Column(children:[_scoreSlider('Performance Score',_num(e['performance_score']),(v)=>setState(()=>_employee={...e,'performance_score':v})),_scoreSlider('Potential Score',_num(e['potential_score']),(v)=>setState(()=>_employee={...e,'potential_score':v}))])),TextFormField(initialValue:'${e['reviewer_comments']}',maxLines:4,onChanged:(v)=>_employee={...e,'reviewer_comments':v},decoration:const InputDecoration(labelText:'Reviewer Comments')),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>_saveReview(e,false),child:const Text('Save Draft'))),const SizedBox(width:10),Expanded(child:FilledButton(onPressed:()=>_saveReview(e,true),child:const Text('Submit Review')))])]);}
  Widget _report(Map<String,dynamic>?e){if(e==null)return const SizedBox();final competencies=_map(e['competency_scores']);final goals=_maps(e['goals']);final goalScore=goals.isEmpty?0:goals.map((g)=>_num(g['progress'])).reduce((a,b)=>a+b)/goals.length/20;final kpi=_map(e['kpis']);final kpiScore=kpi.isEmpty?0:kpi.values.map(_num).reduce((a,b)=>a+b)/kpi.length;final competency=competencies.isEmpty?0:competencies.values.map(_num).reduce((a,b)=>a+b)/competencies.length;return ListView(padding:const EdgeInsets.all(14),children:[_profile(e),CeoCard(child:Column(children:[title('Overall Performance',14),const SizedBox(height:12),SizedBox(width:120,height:120,child:Stack(alignment:Alignment.center,children:[CircularProgressIndicator(value:_num(e['performance_score'])/5,strokeWidth:14,color:CeoColors.cyan,backgroundColor:CeoColors.border),title('${e['performance_score']}/5',20)])),const SizedBox(height:8),title(_num(e['performance_score'])>=4?'Excellent Performer':_num(e['performance_score'])>=3?'Good Performer':'Needs Development',13)])),CeoCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('Score Breakdown',14),_bar('Goals Achievement',goalScore),_bar('KPIs Performance',kpiScore),_bar('Competencies',competency),_bar('Overall Rating',e['performance_score'])])),CeoCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('Summary',14),const SizedBox(height:7),Text('${e['reviewer_comments']}'.isEmpty?'No reviewer summary submitted.':'${e['reviewer_comments']}'),const SizedBox(height:10),_info('Review Date',e['reviewed_at']),_info('Status',e['status'])]))]);}
  Future<void> _saveReview(Map<String,dynamic>e,bool submit)=>_action(submit?'submit_review':'save_review',{'employee_id':e['employee_id'],'performance_score':_employee?['performance_score']??e['performance_score'],'potential_score':_employee?['potential_score']??e['potential_score'],'competency_scores':_employee?['competency_scores']??e['competency_scores'],'reviewer_comments':_employee?['reviewer_comments']??e['reviewer_comments']}).then((_){if(submit&&mounted)setState(()=>_page=4);});
  Future<void> _editGoals(Map<String,dynamic>?e)async{if(e==null)return;final goal=TextEditingController(),progress=TextEditingController(),target=TextEditingController(),kpi=TextEditingController(),kpiScore=TextEditingController();final result=await showDialog<Map<String,dynamic>>(context:context,builder:(c)=>AlertDialog(title:const Text('Add Goal & KPI'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:goal,decoration:const InputDecoration(labelText:'Goal')),TextField(controller:progress,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Progress %')),TextField(controller:target,decoration:const InputDecoration(labelText:'Target Date')),TextField(controller:kpi,decoration:const InputDecoration(labelText:'KPI Name (optional)')),TextField(controller:kpiScore,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'KPI Score / 5'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,{'goal':{'title':goal.text.trim(),'progress':(int.tryParse(progress.text)??0).clamp(0,100),'target_date':target.text.trim()},'kpi_name':kpi.text.trim(),'kpi_score':(double.tryParse(kpiScore.text)??0).clamp(0,5)}),child:const Text('Save'))]));for(final c in[goal,progress,target,kpi,kpiScore])c.dispose();if(result!=null){final kpis=_map(e['kpis']);if('${result['kpi_name']}'.isNotEmpty)kpis['${result['kpi_name']}']=result['kpi_score'];await _action('save_goals',{'employee_id':e['employee_id'],'goals':[..._maps(e['goals']),result['goal']],'kpis':kpis});}}
  Future<void> _changePeriod()async{final c=TextEditingController(text:_period);final v=await showDialog<String>(context:context,builder:(x)=>AlertDialog(title:const Text('Review Period'),content:TextField(controller:c,decoration:const InputDecoration(hintText:'Q2 2026')),actions:[FilledButton(onPressed:()=>Navigator.pop(x,c.text.trim()),child:const Text('Load'))]));c.dispose();if(v!=null&&v.isNotEmpty)setState((){_period=v;_employee=null;_load();});}
  Map<String,dynamic>? _resolve(Map<String,dynamic>d){final l=_maps(d['employees']);if(_employee!=null){final m=l.where((x)=>x['employee_id']==_employee!['employee_id']);if(m.isNotEmpty){final live=m.first;return {...live,'performance_score':_employee!['performance_score']??live['performance_score'],'potential_score':_employee!['potential_score']??live['potential_score'],'competency_scores':_employee!['competency_scores']??live['competency_scores'],'reviewer_comments':_employee!['reviewer_comments']??live['reviewer_comments']};}}return l.isEmpty?null:l.first;}
  Widget _profile(Map<String,dynamic>e)=>CeoCard(child:Row(children:[CircleAvatar(child:Text(_initials('${e['name']}'))),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('${e['name']}',14),muted('${e['designation']} • ${e['department']}',9)]))]));Widget _ratingRow(String n,double v,ValueChanged<double> on)=>Row(children:[Expanded(child:Text(n)),...List.generate(5,(i)=>IconButton(onPressed:()=>on(i+1),icon:Icon(i<v?Icons.star:Icons.star_border,color:CeoColors.cyan,size:19)))]);Widget _scoreSlider(String n,double v,ValueChanged<double>on)=>Column(children:[Row(children:[Expanded(child:Text(n)),Text(v.toStringAsFixed(1))]),Slider(value:v.clamp(0,5).toDouble(),max:5,divisions:10,onChanged:on)]);Widget _bar(String n,dynamic v)=>Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Row(children:[SizedBox(width:120,child:muted(n,9)),Expanded(child:LinearProgressIndicator(value:(_num(v)/5).clamp(0,1).toDouble(),color:CeoColors.green,backgroundColor:CeoColors.border)),const SizedBox(width:8),Text('${_num(v).toStringAsFixed(1)}/5')]));Widget _info(String n,dynamic v)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(children:[SizedBox(width:100,child:muted(n,9)),Expanded(child:Text('${v??'-'}'))]));
  static int _band(dynamic v){final n=_num(v);return n>=4?2:n>=2.5?1:0;}static Map<String,dynamic>_map(dynamic v)=>v is Map?Map<String,dynamic>.from(v):{};static List<Map<String,dynamic>>_maps(dynamic v)=>v is List?v.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():[];static double _num(dynamic v)=>double.tryParse('$v')??0;static String _initials(String n)=>n.split(' ').where((x)=>x.isNotEmpty).take(2).map((x)=>x[0]).join().toUpperCase();static const _titles=['Performance Dashboard','Employee Matrix','Goals & KPIs','Review & Rating','Performance Report'];
}
